version: '3'

vars:
  DIST_DIR: '{{.ROOT_DIR}}/out'
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  BUILD_DATE:
    sh: date '+%Y-%m-%d'
  EPUB_PROJECTS: |
    src/txt/lang-notes/ind

tasks:

  build:
    desc: Build ePub project in the current directory
    cmds:
      - task: build-epub
        vars:
          WORKING_DIR: '{{.USER_WORKING_DIR}}'

  build-all:
    desc: Build all ePub projects
    cmds:
      - for: { var: EPUB_PROJECTS }
        task: build-epub
        vars:
          WORKING_DIR: '{{.ITEM}}'

  build-epub:
    desc: Build ePub
    internal: true
    silent: true
    dir: '{{.WORKING_DIR}}'
    preconditions:
      - test -f ebook.yml
    requires:
      vars:
        - WORKING_DIR
        - DIST_DIR
        - BUILD_DATE
        - GIT_COMMIT
    cmds:
      - cmd: echo 'Building {{.WORKING_DIR}} ...'
      - cmd: |
          xml edit --inplace -N x=http://www.w3.org/2000/svg --update "//x:text[@id='date']" --value "{{.BUILD_DATE}}" --update "//x:text[@id='version']" --value "{{.GIT_COMMIT}}" cover.svg
      - cmd: ebook-cli build
      - cmd: |
          if [ ! -d "{{.DIST_DIR}}" ]; then
            echo "Creating: {{.DIST_DIR}}"
            mkdir -p "{{.DIST_DIR}}"
          fi
          echo "Moving epub to: {{.DIST_DIR}}"
          mv -f *.epub "{{.DIST_DIR}}"/
  
  pdf:
    desc: Convert books to A5 PDF
    dir: '{{.DIST_DIR}}'
    requires:
      vars:
        - DIST_DIR
    cmds:
      - |
        set -e
        export QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox"
        for book in *.epub; do
          ebook-convert ${book} ${book%.epub}.pdf \
            --paper-size a5 \
            --pdf-default-font-size 20 \
            --pdf-add-toc \
            --toc-title "Spis treści" \
            --pdf-page-margin-bottom 36 \
            --pdf-page-margin-left 36 \
            --pdf-page-margin-right 36 \
            --pdf-page-margin-top 36 \
            --pdf-footer-template '<footer><div style="margin: auto;">&mdash; _PAGENUM_ &mdash;</div></footer>'
        done
